### PR TITLE
Capture broadcasted messages for re-broadcasting even at panic

### LINKED ISSUE #236: Testing misbehaving signer
We should test what happens if we have a "faulty" client (lotus) that fails and/or refuses to sign messages (e.g., miner gets restarted, etc.).

### PR DESCRIPTION
**Pull request by masih**
Fix a bug where if `Host.RequestBroadcast` panics the requested message is never added to the re-broadcast state.

Fix an inconsistent behaviour where error at requested broadcasts via re-broadcast are returned instead of being silently logged.

Enhance emulator to allow pluggable signign logic with two additional signing implementation: erroneous and panic.

Implement tests that assert expected behaviour at signing error or panic.

Fixes #236

### CODE REVIEW

File: gpbft/gpbft.go [hunk 1]
```diff
@@ -872,11 +872,17 @@ func (i *instance) broadcast(round uint64, step Phase, value ECChain, createTick
 	if createTicket {
 		mb.BeaconForTicket = i.beacon
 	}
+
+	defer func() {
```
Comment (Stebalien) [inline gpbft/gpbft.go:876]: No need to defer this, we can just do this first.

File: gpbft/gpbft.go [hunk 2]
```diff
@@ -957,10 +963,13 @@ func (i *instance) rebroadcast() error {
 		mbs := i.broadcasted.messagesByRound[round]
 		for _, mb := range mbs {
 			if err := i.participant.host.RequestBroadcast(mb); err != nil {
-				return err
+				// Silently log the error and proceed. This is consistent with the behaviour of
+				// instance for regular broadcasts.
+				i.log("failed to request rebroadcast %s at round %d: %v", mb.Payload.Step, mb.Payload.Round, err)
```
Comment (Stebalien) [inline gpbft/gpbft.go:968]: Hm... it would be nice to sleep and/or backoff a little. But I guess that's a bit difficult.

**Review by Stebalien — APPROVED** [review]
nits

File: gpbft/gpbft.go (hunk 2 above)
Comment (masih) [reply gpbft/gpbft.go:968]: https://github.com/filecoin-project/go-f3/issues/632

Comment (masih) [reply gpbft/gpbft.go:965]: We might be able to use a simple circuit breaker at higher level (e.g. `f3`) to cover this.  Updated the issue description.
