### PR TITLE
Broadcast supplemental data as part of `GMessage`

### LINKED ISSUE #335: Supplemental data is not broadcasted
The supplemental data is not broadcasted. Messages are not received if a participant is passed non-zero supplemental data from `GetProposalForIstance`. When broadcasting is fixed, verification of aggregates fails.

### PR DESCRIPTION
**Pull request by masih**
The supplemental data provided by host is required for additional validation. It is already present in the payload of message builder but not the final `GMessaage`s built from it.

The changes here broadcast supplemental data as part of `GMessage` and enhances simulation to generate a unique supplemental data per instance that is required to be consistent across participant for a given instance.

Fixes #335

### CODE REVIEW

File: gpbft/gpbft.go [hunk 1]
```diff
@@ -69,6 +69,8 @@ type GMessage struct {
 	Ticket Ticket
 	// Justification for this message (some messages must be justified by a strong quorum of messages from some previous step).
 	Justification *Justification
+	// SupplementalData is the additional data to aid validation.
+	SupplementalData SupplementalData
```
Comment (Kubuxu) [inline gpbft/gpbft.go:73]: `SupplementalData` is already part of the Vote

Comment (masih) [reply gpbft/gpbft.go:73]: doh; thanks.

**Review by Stebalien — APPROVED** [review]

**Review by anorth — APPROVED** [review]

**Review by Kubuxu — APPROVED** [review]
