### PR TITLE
Batch insert observed messages using Duckdb appender

### LINKED ISSUE #993: Optimise path to storing messages in observer
When the observer db gets large, the write path slows enough to demand increase in the size of subscription buffer size. Optimise it so that writing messages out is as fast as possible: 

* buffer in memory.
* write to some kind of WAL for crash resistence.
* concurrently dump out to parquet when a size threshold is met.

### PR DESCRIPTION
**Pull request by masih**
For fast batch insertion of messages observed into duckdb, use the native appender to batch the messages based on size or max wait time. Whichever happens first.

Fixes #993

### CODE REVIEW

File: observer/observer.go [hunk 1]
```diff
@@ -200,30 +222,35 @@ func (o *Observer) observe(ctx context.Context) error {
...
 		om.VoteValueKey,
 	); err != nil {
-		return fmt.Errorf("failed to execute query: %w", err)
+		return fmt.Errorf("failed to append row: %w", err)
+	}
+	o.unflushedMessageCount++
+	batchSizeReached := o.unflushedMessageCount >= o.maxBatchSize
+	batchDelayElapsed := !o.lastFlushedAt.IsZero() && time.Since(o.lastFlushedAt) >= o.maxBatchDelay
+	if batchSizeReached || batchDelayElapsed {
+		if err := o.dbAppender.Flush(); err != nil {
```
Comment (Kubuxu) [inline observer/observer.go:248]: Is `Flush` allowed to run concurrently?
I'm thinking, what if we run into low message count again, then the messages won't flush until another message lands.

Comment (masih) [reply observer/observer.go:248]: > Is Flush allowed to run concurrently?

I think it can't (godocs on that function are missing) but it is not being called concurrently in this implementation. 

> what if we run into low message count again, then the messages won't flush until another message lands
Yup good point. I'll adjust the channel to trigger flush on timer. This will be syncronous but would decouple flushing from arrival of messages. Thanks Kuba

**Review by Kubuxu — APPROVED** [review]

**Review by Kubuxu — CHANGES_REQUESTED** [review]
timer won't work

File: observer/observer.go [hunk 2]
```diff
@@ -170,13 +192,15 @@ func (o *Observer) createOrReplaceMessagesView(ctx context.Context, includeParqu
 
 func (o *Observer) observe(ctx context.Context) error {
 	rotation := time.NewTimer(o.rotateInterval)
+	flush := time.NewTimer(o.maxBatchDelay)
```
[the remark this answers is not in the document]
Comment (masih) [reply observer/observer.go:195]: ah man... I have fat fingered this. Sorry.

File: observer/observer.go [hunk 3]
```diff
@@ -169,14 +191,16 @@ func (o *Observer) createOrReplaceMessagesView(ctx context.Context, includeParqu
 }
 
 func (o *Observer) observe(ctx context.Context) error {
-	rotation := time.NewTimer(o.rotateInterval)
+	rotation := time.NewTicker(o.rotateInterval)
+	flush := time.NewTicker(o.maxBatchDelay)
```
Comment (Kubuxu) [inline observer/observer.go:195]: Another note, this will lead to a maximum batch time of 2x maxBatchDelay, but I'm fine with that.

**Review by Kubuxu — APPROVED** [review]
